#!/bin/sh
#
###
# IRT@Nexor
# - cryptroot script sourced from Ubuntu cryptsetup package,
# - and modified to support TPM-LUKS early boot scenarios 
###

PREREQ="cryptroot-prepare"

#
# Standard initramfs preamble
#
prereqs()
{
	# Make sure that cryptroot is run last in local-top
	# IRT@Nexor - ensure this script runs before standard cryptroot..
	for req in $(dirname $0)/*; do
		script=${req##*/}
		#if [ $script != cryptroot-tpm ]; then
			if [ $script != cryptroot ]; then
				echo $script
			fi
		#fi
	done
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# source for log_*_msg() functions, see LP: #272301
. /scripts/functions

#
# Helper functions
#
message()
{
	if [ -x /bin/plymouth ] && plymouth --ping; then
		plymouth message --text="$@"
	else
		echo "$@" >&2
	fi
	return 0
}

udev_settle()
{
	# Wait for udev to be ready, see https://launchpad.net/bugs/85640
	if command -v udevadm >/dev/null 2>&1; then
		udevadm settle --timeout=30
	elif command -v udevsettle >/dev/null 2>&1; then
		udevsettle --timeout=30
	fi
	return 0
}

parse_options()
{
	local cryptopts
	cryptopts="$1"

	if [ -z "$cryptopts" ]; then
		return 1
	fi

	# Defaults
	cryptcipher=aes-cbc-essiv:sha256
	cryptsize=256
	crypthash=ripemd160
	crypttarget=cryptroot
	cryptsource=""
	cryptlvm=""
	cryptkeyscript=""
	cryptkey="" # This is only used as an argument to an eventual keyscript
	crypttries=3
	cryptrootdev=""
	cryptdiscard=""
	CRYPTTAB_OPTIONS=""

	local IFS=" ,"
	for x in $cryptopts; do
		case $x in
		hash=*)
			crypthash=${x#hash=}
			;;
		size=*)
			cryptsize=${x#size=}
			;;
		cipher=*)
			cryptcipher=${x#cipher=}
			;;
		target=*)
			crypttarget=${x#target=}
			export CRYPTTAB_NAME="$crypttarget"
			;;
		source=*)
			cryptsource=${x#source=}
			if [ ${cryptsource#UUID=} != $cryptsource ]; then
				cryptsource="/dev/disk/by-uuid/${cryptsource#UUID=}"
			elif [ ${cryptsource#LABEL=} != $cryptsource ]; then
				cryptsource="/dev/disk/by-label/${cryptsource#LABEL=}"
			fi
			export CRYPTTAB_SOURCE="$cryptsource"
			;;
		lvm=*)
			cryptlvm=${x#lvm=}
			;;
		keyscript=*)
			cryptkeyscript=${x#keyscript=}
			;;
		key=*)
			if [ "${x#key=}" != "none" ]; then
				cryptkey=${x#key=}
			fi
			export CRYPTTAB_KEY="$cryptkey"
			;;
		tries=*)
			crypttries="${x#tries=}"
			case "$crypttries" in
			  *[![:digit:].]*)
				crypttries=3
				;;
			esac
			;;
		rootdev)
			cryptrootdev="yes"
			;;
		discard)
			cryptdiscard="yes"
			;;
		esac
		PARAM="${x%=*}"
		if [ "$PARAM" = "$x" ]; then
			VALUE="yes"
		else
			VALUE="${x#*=}"
		fi
		CRYPTTAB_OPTIONS="$CRYPTTAB_OPTIONS $PARAM"
		eval export CRYPTTAB_OPTION_$PARAM="\"$VALUE\""
	done
	export CRYPTTAB_OPTIONS

	if [ -z "$cryptsource" ]; then
		message "cryptsetup: source parameter missing"
		return 1
	fi
	return 0
}

activate_vg()
{
	# Sanity checks
	if [ ! -x /sbin/lvm ]; then
		message "cryptsetup: lvm is not available"
		return 1
	fi

	# Detect and activate available volume groups
	/sbin/lvm vgscan
	/sbin/lvm vgchange -a y --sysinit
	return $?
}

setup_mapping()
{
	local opts count cryptcreate cryptremove NEWROOT
	opts="$1"

	if [ -z "$opts" ]; then
		return 0
	fi

	parse_options "$opts" || return 1

	if [ -n "$cryptkeyscript" ] && ! type "$cryptkeyscript" >/dev/null; then
		message "cryptsetup: error - script \"$cryptkeyscript\" missing"
		return 1
	fi

	# The same target can be specified multiple times
	# e.g. root and resume lvs-on-lvm-on-crypto
	if [ -e "/dev/mapper/$crypttarget" ]; then
		return 0
	fi

	modprobe -q dm_crypt

	# Make sure the cryptsource device is available
	if [ ! -e $cryptsource ]; then
		activate_vg
	fi

	# If the encrypted source device hasn't shown up yet, give it a
	# little while to deal with removable devices

	# the following lines below have been taken from
	# /usr/share/initramfs-tools/scripts/local, as suggested per
	# https://launchpad.net/bugs/164044
	if [ ! -e "$cryptsource" ]; then
		log_begin_msg "Waiting for encrypted source device..."

		# Default delay is 180s
		if [ -z "${ROOTDELAY}" ]; then
			slumber=180
		else
			slumber=${ROOTDELAY}
		fi

		slumber=$(( ${slumber} * 10 ))
		while [ ! -e "$cryptsource" ]; do
			/bin/sleep 0.1
			slumber=$(( ${slumber} - 1 ))
			[ ${slumber} -gt 0 ] || break
		done

		if [ ${slumber} -gt 0 ]; then
			log_end_msg 0
		else
			log_end_msg 1 || true
		fi
 	fi
	udev_settle

	# We've given up, but we'll let the user fix matters if they can
	while [ ! -e "${cryptsource}" ]; do
		echo "	Check cryptopts=source= bootarg: cat /proc/cmdline"
		echo "	or missing modules, devices: cat /proc/modules; ls /dev"
		panic -r "ALERT!  ${cryptsource} does not exist.  Dropping to a shell!"
	done

	# Prepare commands
	cryptcreate="/sbin/cryptsetup -T 1"
	if [ "$cryptdiscard" = "yes" ]; then
		cryptcreate="$cryptcreate --allow-discards"
	fi
	if /sbin/cryptsetup isLuks $cryptsource >/dev/null 2>&1; then
		cryptcreate="$cryptcreate luksOpen $cryptsource $crypttarget"
	else
		cryptcreate="$cryptcreate -c $cryptcipher -s $cryptsize -h $crypthash create $crypttarget $cryptsource"
	fi
	cryptremove="/sbin/cryptsetup remove $crypttarget"
	NEWROOT="/dev/mapper/$crypttarget"

	#################################################################
	# IRT@Nexor - determine if any suitable TPM indexes exist 	#
	#################################################################
	# IRT@Nexor - we need to check for PCR composites, to determine if we try TPM-based LUKS unlock or not.. 
	# IRT@Nexor - script fragment borrowed from cryptroot-ask-tpm.sh.. 
	GETCAP=/usr/bin/getcapability
	AWK=/usr/bin/awk
	TPM_LUKS_MAX_NV_INDEX=128
	VIABLE_INDEXES=""
	# An index is viable if its composite hash matches current PCR state, or if
	# it doesn't require PCR state at all
	#
	ALL_INDEXES=$($GETCAP -cap 0xd | ${AWK} -F: '$1 ~ /Index/ {print $2 }' | ${AWK} -F= '{ print $1 }')
	for i in $ALL_INDEXES; do
		MATCH1=$($GETCAP -cap 0x11 -scap $i | ${AWK} -F ": " '$1 ~ /Matches/ { print $2 }')
		if [ -n "${MATCH1}" -a "${MATCH1}" = "Yes" ]; then
			# Add this index at the beginning, since its especially likely to be
			# the index we're looking for
			VIABLE_INDEXES="$i $VIABLE_INDEXES"
			echo "PCR composite matches for index: $i"
			continue
		elif [ $i -gt ${TPM_LUKS_MAX_NV_INDEX} ]; then
			continue
		fi

		# Add this index at the end of the list
		VIABLE_INDEXES="$VIABLE_INDEXES $i"
		echo "Viable index: $i"
	done

	# IRT@Nexor - our default keyfile location:
	KEYFILE=/plain_key

	# Try to get a satisfactory password $crypttries times
	count=0
	while [ $crypttries -le 0 ] || [ $count -lt $crypttries ]; do
		export CRYPTTAB_TRIED="$crypttries"
		count=$(( $count + 1 ))

		if [ $count -gt 1 ]; then
			/bin/sleep 3
		fi

		if [ -z "$cryptkeyscript" ]; then
			cryptkey1="Unlocking the disk $cryptsource ($crypttarget)\nEnter NV AREA passphrase: "
			cryptkey2="Unlocking the disk $cryptsource ($crypttarget)\nEnter LUKS passphrase: "
			if [ -x /bin/plymouth ] && plymouth --ping; then
				cryptkeyscript="plymouth ask-for-password --prompt"
				cryptkey1=$(printf "$cryptkey1")
				cryptkey2=$(printf "$cryptkey2")
			else
				cryptkeyscript="/lib/cryptsetup/askpass"
			fi
		fi


		if [ ! -e "$NEWROOT" ]; then
			# flock against other interactive activities
			{ flock -s 9;
				crypttarget="$crypttarget"
				cryptsource="$cryptsource"
				# IRT@Nexor - If we found some viable TPM indexes, try TPM-LUKS unlock first.. 
				if [ "$VIABLE_INDEXES" != "" ]; then
					# IRT@Nexor - Attempt passwordless key release first.. 
					/sbin/cryptroot-dontask-tpm $cryptsource $crypttarget
					# IRT@Nexor - If still no joy, request a password.. 
					if [ ! -e "$NEWROOT" ]; then
						$cryptkeyscript "$cryptkey1" | /sbin/cryptroot-ask-tpm $cryptsource $crypttarget
					fi
				fi
			} 9>/.console.lock
		fi
			
		if [ ! -e "$NEWROOT" ]; then
			echo "WARNING: Nexor strongly recommends sealing this system to it's TPM!"
			echo "Enable / own your TPM and run 'tpm-luks-init' from maintenance mode"
			echo "No viable TPM indexes found, falling back to LUKS keyfile / passphrase.."
			# First attempt to use our default keyfile if it exists.. 
			{ flock -s 9;
				if [ -f $KEYFILE ]; then
					/sbin/cryptsetup luksOpen -T1 $cryptsource $crypttarget --key-file=$KEYFILE --batch-mode
				fi
				if [ ! -e "$NEWROOT" ]; then
				# IRT@Nexor - Finally, attempt using LUKS passphrase direct.. 
					#$cryptkeyscript "$cryptkey2" --command="$cryptcreate"
					$cryptkeyscript "$cryptkey2" | $cryptcreate --key-file=-
				fi
				if [ ! -e "$NEWROOT" ]; then
					message "cryptsetup: cryptsetup failed, bad password or options?"
					continue
				fi
			} 9>/.console.lock
		fi

		if [ ! -e "$NEWROOT" ]; then
			message "cryptsetup: unknown error setting up device mapping"
			return 1
		fi

		#FSTYPE=''
		#eval $(fstype < "$NEWROOT")
		FSTYPE="$(/sbin/blkid -s TYPE -o value "$NEWROOT")"

		# See if we need to setup lvm on the crypto device
		#if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
		if [ "$FSTYPE" = "LVM_member" ] || [ "$FSTYPE" = "LVM2_member" ]; then
			if [ -z "$cryptlvm" ]; then
				message "cryptsetup: lvm fs found but no lvm configured"
				return 1
			elif ! activate_vg; then
				# disable error message, LP: #151532
				#message "cryptsetup: failed to setup lvm device"
				return 1
			fi

			NEWROOT=${cmdline_root:-/dev/mapper/$cryptlvm}
			if [ "$cryptrootdev" = "yes" ]; then
				# required for lilo to find the root device
				echo "ROOT=$NEWROOT" >>/conf/param.conf
			fi
			eval $(fstype < "$NEWROOT")
		fi

		#if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
		if [ -z "$FSTYPE" ]; then
			message "cryptsetup: unknown fstype, bad password or options?"
			udev_settle
			$cryptremove
			continue
		fi

		message "cryptsetup: $crypttarget set up successfully"
		break
	done

	if [ $crypttries -gt 0 ] && [ $count -gt $crypttries ]; then
		message "cryptsetup: maximum number of tries exceeded for $crypttarget"
		return 1
	fi

	udev_settle
	return 0
}

#
# Begin real processing
#

# Do we have any kernel boot arguments?
cmdline_cryptopts=''
unset cmdline_root
for opt in $(cat /proc/cmdline); do
	case $opt in
	cryptopts=*)
		opt="${opt#cryptopts=}"
		if [ -n "$opt" ]; then
			if [ -n "$cmdline_cryptopts" ]; then
				cmdline_cryptopts="$cmdline_cryptopts $opt"
			else
				cmdline_cryptopts="$opt"
			fi
		fi
		;;
	root=*)
		opt="${opt#root=}"
		case $opt in
		/*) # Absolute path given. Not lilo major/minor number.
			cmdline_root=$opt
			;;
		*) # lilo major/minor number (See #398957). Ignore
		esac
		;;
	esac
done

if [ -n "$cmdline_cryptopts" ]; then
	# Call setup_mapping separately for each possible cryptopts= setting
	for cryptopt in $cmdline_cryptopts; do
		setup_mapping "$cryptopt"
	done
	exit 0
fi

# Do we have any settings from the /conf/conf.d/cryptroot file?
if [ -r /conf/conf.d/cryptroot ]; then
	while read mapping <&3; do
		setup_mapping "$mapping" 3<&-
	done 3< /conf/conf.d/cryptroot
fi

exit 0
