#!/bin/bash

if grep -q nash /usr/libexec/plymouth/plymouth-populate-initrd \
   || ! grep -q PLYMOUTH_POPULATE_SOURCE_FUNCTIONS /usr/libexec/plymouth/plymouth-populate-initrd \
   || [ ! -x /usr/libexec/plymouth/plymouth-populate-initrd ]; then
    . "$moddir"/plymouth-populate-initrd
else
    PLYMOUTH_POPULATE_SOURCE_FUNCTIONS="$dracutfunctions" \
        /usr/libexec/plymouth/plymouth-populate-initrd -t $initdir
fi

inst_hook pre-pivot 90 "$moddir"/plymouth-newroot.sh
inst_hook pre-trigger 10 "$moddir"/plymouth-pretrigger.sh
inst_hook emergency 00 "$moddir"/plymouth-emergency.sh
inst "$moddir"/cryptroot-ask.sh /sbin/cryptroot-ask
inst readlink
# tpm-luks dependencies
inst "$moddir"/cryptroot-ask-tpm.sh /sbin/cryptroot-ask-tpm
# IRT@Nexor - deliver our additional non-interactive NV area unseal script: 
inst "$moddir"/cryptroot-dontask-tpm.sh /sbin/cryptroot-dontask-tpm
# IRT@Nexor - IF we provide a plain_key within the plymouth-tpm module directory, 
# incorporate this also into our new initial ramdisk.. 
if [ -f "$moddir"/plain_key ]; then
	inst "$moddir"/plain_key /plain_key
fi
inst_binary getcapability
inst_binary awk
inst_binary od
inst_binary nv_readvalue
